app = "dubbha-remix-jokes"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source="remix_jokes_data"
  destination="/data"
